name: 'Publication to registry smoke tester'
on:
  push:
    branches:
      - "master"

jobs:
  action-smoker:
    runs-on: [ self-hosted, Linux, k8s ]
    outputs:
      publish-outcome: ${{ steps.registry-publication-action.outputs.report }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Preparing docker images for smoke test
        run: |
          docker pull busybox
          docker tag busybox busybox:0.0.1-SNAPSHOT

          docker pull hello-world
          docker tag hello-world hello-world:0.0.1-SNAPSHOT

      - name: Run publication to registry
        id: registry-publication-action
        continue-on-error: false
        uses: ./
        with:
          ARTIFACTS_CONFIG_FILE: ".github/artifacts.yaml"
          ARTIFACTORY_APIKEY:    ${{ secrets.VC_ART_API_KEY }}
          ARTIFACTORY_USER:      ${{ secrets.VC_ART_USER }}
          BUILD_NUMBER:          ${{ github.run_number }}
          BUILD_NAME:            ${{ github.job }}
          BUILD_VERSION:         "0.0.1-SNAPSHOT"
          WORKSPACE:             ${{ github.workspace }} #${GITHUB_WORKSPACE}
          BUILD_URL:             ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Docker Images
        run: docker images
        shell: bash
