name: 'Publication to registry smoke tester'
on:
  push:
    branches:
      - "YKN-6"

jobs:
  action-smoker:
    runs-on: [ self-hosted, Linux, k8s ]
    outputs:
      publish-outcome: ${{ steps.registry-publication-action.outputs.report }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Preparing docker images for smoke test
        run: |
          docker pull busybox
          docker tag busybox golden-vc-docker.repo.orl.eng.hitachivantara.com/busybox

          docker pull hello-world
          docker tag hello-world golden-vc-docker.repo.orl.eng.hitachivantara.com/hello-world

      - name: Run publication to registry
        id: registry-publication-action
        continue-on-error: false
        uses: ./
        with:
          IMAGES: |
            golden-vc-docker.repo.orl.eng.hitachivantara.com/busybox
            golden-vc-docker.repo.orl.eng.hitachivantara.com/hello-world
          HELM_CHARTS: |
            ./.github/resources/my-chart-1-0.0.1.tgz
            ./.github/resources/my-chart-2-0.0.1.tgz
            ./.github/resources/my-chart-3-0.0.1.tgz
          ARTIFACTORY_URL:         "https://repo.orl.eng.hitachivantara.com/artifactory/"
          ARTIFACTORY_APIKEY:      ${{ secrets.VC_ART_API_KEY }}
          ARTIFACTORY_USER:        ${{ secrets.VC_ART_USER }}
          ARTIFACTORY_HELM_REPO:   "temp-helm"
          ARTIFACTORY_DOCKER_REPO: "golden-vc-docker"
          BUILD_NUMBER:            ${{ github.run_number }}
          BUILD_NAME:              ${{ github.job }}
          WORKSPACE:               ${{ github.workspace }}

      - name: Get publication outcome
        run: echo "Publish outcome was ${{ steps.registry-publication-action.outputs.publish-outcome }}"
